### ISSUE TITLE
Continuous crashes

### ISSUE THREAD

**Issue by LexonFlipao** [mikkokko/csldr#1]
I've been using this .dll recently, and the error occurs when I put new weapons into the game.

Example:
My game has all the weapons modified, some of them don't cause me an error, but when I choose a specific one (the ak47 or the m249) the game closes, I've tried replacing them with other weapons, but when I do that, other weapons give me said crash, I don't get the error in this case why this happens, I don't know if it will have any kind of solution

**Comment by mikkokko** [comment]
Can you send the models that cause the crash?

**Comment by LexonFlipao** [comment]
> Can you send the models that cause the crash?

[Crashed weapons.zip](https://github.com/mikkokko/csldr/files/8855602/Crashed.weapons.zip)

**Comment by LexonFlipao** [comment]
> Can't replicate the crash, what version of the game are you using?

CS Warzone

**Comment by mikkokko** [comment]
Can't replicate it on warzone either. You should probably try if it crashes on a clean installation with only the dll and the skins installed.

**Comment by LexonFlipao** [comment]
> Can't replicate it on warzone either. You should probably try if it crashes on a clean installation with only the dll and the skins installed.

maybe you should try with the full pack, this error always happen when i got all my weapons modificated

**Comment by mikkokko** [comment]
Fixed in https://github.com/mikkokko/csldr/commit/f2f98797eaa628ce03f03a0511cd9249e41ad170.
