### ISSUE TITLE
xhair don't disapear when should

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#11]
### Expected result
xhair disapear like normal crosshair when:
- client cvar `hud_draw` is 0
- recived message [HideWeapon](https://wiki.alliedmods.net/Half-Life_1_Game_Events#HideWeapon)  with `(1<<6)` arg (this is HIDEHUD_CROSSHAIR)

### Real result
xhair don't disapear

**Comment by mikkokko** [comment]
Thanks, fixed in https://github.com/mikkokko/csldr/commit/56da929f757fb7561fee1e029e8f5231de4c2354 and https://github.com/mikkokko/csldr/commit/3cd866f834d068f34b547e10600e226feb9055cd.
