### ISSUE TITLE
Cant' set floating point values

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#12]
Hello @mikkokko, after last update, I can't set floating point values to **_some_** xhair_* vars.
For example: I set my xhair_gap to 2.4. This is the optimal and pleasant value for me. But now it can be only 2 or 3, I mean only integers, other values just don't change anything.
Or another cvar: xhair_thick. It behaved strangely before, it only worked at 0, 0.5, and more than 1. 
But now not even 0.5 works! Only 0, 1, 2, etc.
But 0 is too little for me, and 1 is too much.

**Comment by mikkokko** [comment]
Thanks, fixed in https://github.com/mikkokko/csldr/commit/a4cd44d7d1a3778dba93a4a7ed7e623e9c09edcd.
