### ISSUE TITLE
About renderer

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#13]
Hey mikkokko, I have tested the new feature (renderer) and I have some questions and reports about it.

## Performance tests
Tested on Linux client, GPU: RTX 3070Ti
Studio info:
```
OpenGL version: 4.6.0 NVIDIA 530.41.03
GL_ARB_uniform_buffer_object: available
Fast path: available
GPU skinning: enabled
```
I found a player model that has ~54k polygons, set it to 30 bots and looked at the fps.

Total number of e-poly in these screenshots: __1 624 526__

`studio_fastpath 0`: 14 fps

![20230428085707_1](https://user-images.githubusercontent.com/47604048/235067494-e90e747c-2f1a-49c3-a28c-dacfa1ab7a32.jpg)

`studio_fastpath 1`: 200+ fps

![20230428085721_1](https://user-images.githubusercontent.com/47604048/235067539-14d5f9f7-3a79-4448-85a2-2fb5642a1ebd.jpg)

It works perfectly for hi-poly models!
BUT.

## Issues
1. As you said in readme, "some parts are too dark and others too light". Can this be fixed?
2. Also "Elights are not handled". (I have elight for a flashlight on my server, I would appreciate ir if this could be fixed)
3. pev_renderfx `kRenderTransAlpha` doesn't work. This is bad because many servers use it to make players invisible.
4. `kRenderGlow` + `kRenderFxGlowShell` does not work - game crashes instantly. This is just as bad because many servers use kRenderFxGlowShell. I think even more than kRenderTransAlpha.
5. I did some playtests on the servers. __Sometimes the game just randomly crashes__. Maybe there was an entity with kRenderFxGlowShell appears at these moments, but I haven't seen it, I don't know. Sometimes it happened right after connecting to the server.
6. `r_speed` doesn't show epoly, but I was expecting that.

## Questions
>Custom rendermodes are not implemented (haven't bothered, rarely seen in-game like chrome)
1. What is custom rendermodes? Did you mean pev_rendermode?
>Rendering of hulls, bboxes or bones is not supported
2. What exactly does this mean? I haven't seen them rendered in a normal game.
>Chrome rendering is wrong
3. What is this? Did you mean a "chrome" effect on view model? (on screenshot studio_fastpath is 0)

![20230428102416_1](https://user-images.githubusercontent.com/47604048/235082636-b920c25e-d923-406d-abe0-c132b4e3fae2.jpg)

If so, it seems to work with studio_fastpath 1.

# Summarizing
The new feature works, but needs some fine-tuning for playing.
And...
The topic I wanted to raise the fact that the performance of the game unfortunately can not be raised only the new rendering models. This is cool to play on fully modded servers, such as Zombie Plague (+ cso mod) or CS:GO mod. They often use models with a lot of polygons. __But.__ The game also requires a new world renderer. Can you do that?
World polygons as well as models, with the current rendering greatly reduce the performance of the game.
For eg: on my server (without hi-poly models) the new renderer gives only +10-30 fps, no more... And I mean at a total of 500+ fps, so it's not even 10%
Another example: I have ~1100 fps with 8 wpoly and ~600 fps with 1078 epoly. And this is still on an empty listenserver with no models! And with my GPU. ___Imagine what happens on weak PCs on live servers.___

**Comment by Nord1cWarr1or** [comment]
I tested the updated version - yes, now there are no crashes and all the rendering effects work. And the brightness of the models is fine.

But there is one small defect with kRenderFxGlowShell effect, when it is applied to some object, some other objects become semi-transparent for some reason.

Examples:

![20230504204442_1](https://user-images.githubusercontent.com/47604048/236476227-dcad9cfa-451f-443c-948f-4f9eee54ea5b.jpg)

![20230504204445_1](https://user-images.githubusercontent.com/47604048/236476251-1c9a1c1f-f1ee-4578-9c54-8ca08dbf2add.jpg)

However, it happens as if from a certain angle of view:

(no bug)

![20230504204647_1](https://user-images.githubusercontent.com/47604048/236476569-c6aee81e-03bd-4627-bb45-ccb9f3f0714b.jpg)

![20230504204729_1](https://user-images.githubusercontent.com/47604048/236476690-bfbcb71d-12c6-4f9e-9f0c-51fa582aac46.jpg)

![20230504204731_1](https://user-images.githubusercontent.com/47604048/236476738-eaba9d90-7b24-41ce-aab7-1b1a2d301f6e.jpg)

![20230504204828_1](https://user-images.githubusercontent.com/47604048/236476900-a78feb25-a091-4071-bd6b-b87e84c7a492.jpg)

![20230504204832_1](https://user-images.githubusercontent.com/47604048/236476970-3f6ec0db-8587-4128-83be-69c13a1baaa6.jpg)

(p_* model becomes transparent)

![20230504205227_1](https://user-images.githubusercontent.com/47604048/236477105-f17b8d61-818c-48c5-a2f0-298f6b97ce51.jpg)

When the glow effect is applied to an entity, the bug happens to other entities, but not to players. When the glow effect is applied to a player, the bug appears on players, but not on other entities:

![20230504205315_1](https://user-images.githubusercontent.com/47604048/236477839-77499b87-71a8-4f3d-bd6e-cd8d161d2dea.jpg)

![20230504205331_1](https://user-images.githubusercontent.com/47604048/236477893-0dda162d-7bc6-4656-b0ce-2ce3b1f4f89a.jpg)

**Comment by mikkokko** [comment]
This should be fixed in https://github.com/mikkokko/csldr/commit/19bf2d5f96fcac279b1bf450784eb23d62d77389. Elights are also implemented now.

**Comment by Nord1cWarr1or** [comment]
Everything seems to be working fine now. I'll let you know if I find any more flaws.

I also have to say that I get a warning when I compile:
![pic](https://user-images.githubusercontent.com/47604048/236699526-8e936a4c-36b3-4304-91df-cf9910c646e4.png)

And
>Eventually I would like to write a custom world renderer, though writing a fully featured one within client.dll would be quite a lot of work.

It will be great if you can make a new world rendering. I could help with playtests.
