### ISSUE TITLE
Qeustion about viewmodel_hands and camera_movement

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#14]
Can you please explain in more detail what I have to do to make camera_movement work?

>To get bone controlled camera movement working, make a bone called "camera" and make an attachment on it.

It's not quite clear. This bone has to be added to the player model? Or to the view model?
And where do I place it?

And about hands.. What should the hand model contain? Can you show an example?

**Comment by mikkokko** [comment]
Here's an example model that uses the animated camera feature: https://gamebanana.com/mods/382062
viewmodel_hands is simply the hand model separated from the viewmodel: [Uusi kansio (6).zip](https://github.com/mikkokko/csldr/files/11505638/Uusi.kansio.6.zip)

**Comment by Nord1cWarr1or** [comment]
Thanks
