### ISSUE TITLE
Texture replacement broke the display of models

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#16]
The player models on which I tested performance are now displayed incorrectly. Some parts of the model are missing, such as hair and feathers on the sleeves

before changes

![20230522115020_1](https://github.com/mikkokko/csldr/assets/47604048/5458640e-7d06-48aa-9cf3-f61016751841)

new build

![20230522115129_1](https://github.com/mikkokko/csldr/assets/47604048/da7fa8a1-7aec-460a-a1fb-da4e0260c6d7)
![20230522115131_1](https://github.com/mikkokko/csldr/assets/47604048/19ab4e18-68e5-477f-9a6d-9ae98e22388c)

**Comment by mikkokko** [comment]
Should be fixed in https://github.com/mikkokko/csldr/commit/f4d0333786361b985604c7577e1b94c081e1d58b.

**Comment by mikkokko** [comment]
Fixed in https://github.com/mikkokko/csldr/commit/29b49a8688d4aba03e86d3762e49b855fd999747.

**Comment by Nord1cWarr1or** [comment]
Confirmed, everything is fine now.
