### ISSUE TITLE
plssssssss, made another one 

### ISSUE THREAD

**Issue by lightblue123** [mikkokko/csldr#17]
plsssssssss make another one i just want this features take your time i will wait forever just make it for me plssssssssssssssssssssssss 

1-dll with Shell,c and h only
one dll and other one plsssss

2-dll with...

...Shell,c and h 
inspect,c and h (that csgo inspect plsssssss)
If you need something tell me i will do anything for you

**Comment by mikkokko** [comment]
You can disable all of the other features with [cvars](https://github.com/mikkokko/csldr#cvars-and-commands). If the presence of other features really bothers you for some reason, you'll have to remove them out yourself.

**Comment by lightblue123** [comment]
plssssssssss mate make the both for me plssssssssssssssss
i cant remove it i dont know modify im very noob i dont know anything
i cant disable the cvars because the game dont start because some features crash it the error is GUI error plsssssss mate i love you make the both for me pls :( or just make one i will wait 1 month or 2 months just make it for me pls :( im noob ;((((((
