### ISSUE TITLE
[request] Dynamic xhair

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#18]
Can you make a custom crosshair dynamic? So that it widens when firing, like a normal one. (but so that its widening speed doesn't depend on fps)
I found another open source project where there is a custom crosshair, and there it has an widening when firing. Maybe this code can help in development. https://github.com/oxiKKK/oxware/blob/main/src/cheat/features/VanillaCrosshair.cpp#L138
And you could make a CVar, like `xhair_dynamic 0/1`

**Comment by mikkokko** [comment]
I'm planning to implement it eventually. I haven't done it yet because I'd need to manually track some of the variables it needs like the amount of shots fired.

**Comment by Nord1cWarr1or** [comment]
> I'm planning to implement it eventually. I haven't done it yet because I'd need to manually track some of the variables it needs like the amount of shots fired.

Glad to hear it, I'll be waiting

**Comment by lightblue123** [comment]
> I'm planning to implement it eventually. I haven't done it yet because I'd need to manually track some of the variables it needs like the amount of shots fired.

Sir, could you make that dlls for me please, i'm really like the game please make it for me i want that i want to keep playing the game: :(

Dll 1-
With only shell (shell changes the out position)

Dll 2-
only with shell and csgo inspect weapon

i will wait as you want, i will wait 1 month or even 2 please dont make me sad
thanks for reply and thank you for that cool mod and youre smart guy keep modfiy anything you want and enjoy 👍
