### ISSUE TITLE
Shaders must be stored separately?

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#19]
After the last update I can not delete the folder with the sources where I compile, because of an error when I launch the game: 
![pic](https://github.com/mikkokko/csldr/assets/47604048/25f1b10c-ba70-45d6-93dd-7d8da92e1a5b)

**Comment by mikkokko** [comment]
Caused by a blunder in CMakeLists.txt, pushed a commit that fixes it.
