### ISSUE TITLE
Game does not launch on Linux

### ISSUE THREAD

**Issue by ghost** [mikkokko/csldr#2]
System info: [system_info.txt](https://github.com/mikkokko/csldr/files/8936205/system_info.txt)
Core dump: https://files.catbox.moe/dqmiiy.7z
GDB log + backtrace: [hl_linux_gdb.txt](https://github.com/mikkokko/csldr/files/8936210/hl_linux_gdb.txt)

**Comment by mikkokko** [comment]
Looks like it's dlopen failing on client_orig.so. Add something like this to Plat_Dlopen in platform_linux.c to see what path it tries to load it from and why it fails.
```c
void *Plat_Dlopen(const char *filename)
{
    void *handle;
    handle = dlopen(filename, RTLD_NOW);
    if (!handle)
        fprintf(stderr, "dlopen %s failed: %s\n", filename, dlerror());
    return handle;
}
```
