### ISSUE TITLE
How to preserve the animation of viewhands in MDL

### ISSUE THREAD

**Issue by Mandarinkocka** [mikkokko/csldr#22]
I really like the function of specifying viewhands, which can greatly avoid many meaningless resource loads. But how can we make the skeletal animation of viewhands not lost when compiling mdl

**Comment by mikkokko** [comment]
You can use [Sven Co-op studiomdl's $keepallbones qc option](https://the303.org/tutorials/gold_qc.htm#AS).

**Comment by Mandarinkocka** [comment]
Thank you. I have a doubt, does "event 6001" take effect in CS? I remember that 6001 in the half-life it was possible to eject the cartridge case in Annex 2
