### ISSUE TITLE
vac status

### ISSUE THREAD

**Issue by fred0r** [mikkokko/csldr#26]
i am aware of `Play on VAC secured servers at your own risk` - which has been mentioned in https://github.com/mikkokko/csldr/commit/424faad35afd101ff4c33ff0bd227fe95ed27954 .
is there - beside this place - another forum/site covering the current vac-status?
main reason for me to use csldr would be the `Hor+ FOV scaling for widescreen` feature on linux.

**Comment by mikkokko** [comment]
> is there - beside this place - another forum/site covering the current vac-status?

Nope

I'll update the readme if i hear about someone getting banned (which i doubt will ever happen).
