### ISSUE TITLE
Crash in `BuildStudioVBO` with giant studiomodel

### ISSUE THREAD

**Issue by Xelson** [mikkokko/csldr#28]
I'm got a crash in `BuldStudioVBO` while connecting on Counter-Strike 1.6 server `62.122.215.44:27030`
![alt text](https://i.postimg.cc/wBYGZLTJ/image.png)

Looks like the cache was broken somewhere
![alt text](https://i.postimg.cc/SK53d3YS/image.png)

**Comment by mikkokko** [comment]
Yeah, the vbo building code uses a lot of fixed size arrays and hardly does any bounds checking so very large models can crash it. Can you upload the model that's causing the crash?

**Comment by Xelson** [comment]
sure, [part01_b04.mdl](https://service.next21.ru/fastdl/models/next21_scp/foundation/part01_b04.mdl)

**Comment by mikkokko** [comment]
Fixed in 505581c0fbf3b89b2652fe64fcb901a72335b31a.
