### ISSUE TITLE
FOV

### ISSUE THREAD

**Issue by haophan1996** [mikkokko/csldr#3]
hello developer, Is there something  wrong when viewmodel_fov is Unknown command

**Comment by mikkokko** [comment]
What version of the game are you running? viewmodel_fov won't registered if the game thinks you're running with the software renderer. The check is pretty sloppy since it just checks if the engine library is called hw.dll.

**Comment by haophan1996** [comment]
I have no idea what version Im using, maybe very old one

**Comment by mikkokko** [comment]
Try if it works now with the latest release.

**Comment by haophan1996** [comment]
hmm, now it show cvar, viewmodel_fov, but viewmodel does not change

**Comment by mikkokko** [comment]
Does the game print a message about software mode to the console when launched? Also make sure you aren't using D3D, viewmodel fov won't work with it either because of the crippled translation layer they used.

**Comment by haophan1996** [comment]
No, i did not see any message in console when launch. I'm really sure im using opengl, maybe im using version too old.
from console I entered command version, version, and it shows like this
version 
Protocol version 47
Exe version 1.1.2.6 (cstrike)
Exe build: 10:56:59 Oct  3 2005 (3266)

**Comment by mikkokko** [comment]
That itself shouldn't be an issue since i've tried this on builds from 2003 without any problems.

**Comment by haophan1996** [comment]
thank you, its working like a charm

**Comment by mikkokko** [comment]
What ended up fixing it?

**Comment by haophan1996** [comment]
i think i use metahook and it override fov somehow, so it might not working

**Comment by mikkokko** [comment]
That makes sense, should probably add a note about it to the readme.
