### ISSUE TITLE
Viewmodel remapping colors are not supported

### ISSUE THREAD

**Issue by Xelson** [mikkokko/csldr#30]
Viewmodel remapping colors are handling incorrectly

with `studio_fastpath 1`
![35hp_2efk0000](https://github.com/mikkokko/csldr/assets/43149567/ce8c9a8b-6693-4034-bf75-038029b49dab)
with `studio_fastpath 0`
![35hp_2efk0001](https://github.com/mikkokko/csldr/assets/43149567/03e14768-0bc3-4f46-8495-9fce156b1e40)

the viewmodel file:
[v_tentacles_knife_b02.zip](https://github.com/mikkokko/csldr/files/12837886/v_tentacles_knife_b02.zip)

**Comment by Xelson** [comment]
i'm sorry i was wrong, it's actually `topcolor` and probably `bottomcolor` has the same issue

**Comment by mikkokko** [comment]
Fixed in c3711058f325dcf4a56b72324c055c03a932f297.
