### ISSUE TITLE
Texture problems 

### ISSUE THREAD

**Issue by Xelson** [mikkokko/csldr#31]
Some models are losing their textures under unclear circumstances since https://github.com/mikkokko/csldr/commit/c3711058f325dcf4a56b72324c055c03a932f297

`studio_fastpath 0`:
![0](https://github.com/mikkokko/csldr/assets/43149567/c57912ea-1aef-4fef-a7ab-806553997f82)
`studio_fastpath 1`:
![1](https://github.com/mikkokko/csldr/assets/43149567/3a272696-c85c-495e-b364-d39e7a1aa728)

**Comment by mikkokko** [comment]
Should be fixed in b7e6867afeb2ba94c68d9f469f43b9c6272f30d0.
