### ISSUE TITLE
Significant loss of performance with tempentities

### ISSUE THREAD

**Issue by Xelson** [mikkokko/csldr#32]
Tested on https://github.com/mikkokko/csldr/commit/caecabf505b432420075b20d64546a55f31cdd99

The screenshots show the result of sending the `SVC_TEMPENTITY` message with `TE_BREAKMODEL` key:
`studio_fastpath 0`, after appearance, average fps is `~90`
![2](https://github.com/mikkokko/csldr/assets/43149567/914e37e9-3fa7-4648-85b0-de81d8e80e01)
`studio_fastpath 0`, after disappearing, average fps is `140`
![1](https://github.com/mikkokko/csldr/assets/43149567/a3fb5f27-2794-4303-9749-fc28289fd6ee)

`studio_fastpath 1`, after appearance, average fps is `~40`
![3](https://github.com/mikkokko/csldr/assets/43149567/624afecb-0a51-4698-a842-8a1f0f15cc62)
`studio_fastpath 1`, after disappearing, average fps is `140`
![4](https://github.com/mikkokko/csldr/assets/43149567/c8239fb4-856e-4bd6-bc9e-16c80dbdc0eb)

**Comment by mikkokko** [comment]
I can't seem to replicate this with any of the hardware I have at hand. What GPU do you have? Does the performance also tank before 505581c0fbf3b89b2652fe64fcb901a72335b31a?

**Comment by Xelson** [comment]
> What GPU do you have?

I have `GTX 950`

> Does the performance also tank before 505581c

Yeah I'm experiencing the same issue on 921df975
![ka_spires_lava0001](https://github.com/mikkokko/csldr/assets/43149567/4ec64f3b-96c3-484e-a1f4-45118e48c2e4)
![ka_spires_lava0002](https://github.com/mikkokko/csldr/assets/43149567/b73f3673-b2ce-4750-9338-373358f1c098)

**Comment by mikkokko** [comment]
I've pushed a rough version of a shader combo system to the [shader_combo](/mikkokko/csldr/tree/shader_combo) branch, let me know if this helps with performance at all.

**Comment by Xelson** [comment]
At the moment I am experiencing problems with running csldr at all after I migrated the system to a new ssd. I will do an issue about that firstly

**Comment by Xelson** [comment]
There are errors with the crash of the game when switching to `studio_fastpath 1`
![image](https://github.com/mikkokko/csldr/assets/43149567/2fac8676-8069-45da-b6e1-bcb21a3f7911)

**Comment by mikkokko** [comment]
Try replacing `#version 140` on [this line](https://github.com/mikkokko/csldr/blob/3839d8836673316352ef40fd5f24341ba73e181a/csldr/studio_render.c#L222C2-L222C2) with `#version 150 compatibility`.

**Comment by Xelson** [comment]
it helped but after I minimized the game, something happened and another error appeared. 
![image](https://github.com/mikkokko/csldr/assets/43149567/33a837a3-d15c-4806-8b2b-b24eba589540)
and in any case, there have been no significant improvements, FPS was increased to `~60` but it's still 40% worse than the vanilla renderer
![35hp_2efk0002](https://github.com/mikkokko/csldr/assets/43149567/c2dbe0af-8215-4a56-832e-4166083a546a)

**Comment by mikkokko** [comment]
Welp, In that case I guess the main bottleneck is the huge amount of opengl state changes that has to be done every time a model is rendered.

This could be solved by building a model queue and rendering them all in one go but this would cause issues with the rendering order of transparent entities. Only proper solution would be to move the rendering of all entities to client, which would be quite a lot of work.

**Comment by mikkokko** [comment]
Merged my old queue code in and pushed it to the model_queue branch. Rendering order of everything will be broken but it should work well enough for testing. Let me know if it helps, if it does it might be worth it to implement a proper rendering queue.

**Comment by Xelson** [comment]
it has become much better

`studio_fastpath 0`
![35hp_nahuatl0014](https://github.com/mikkokko/csldr/assets/43149567/b356e28c-5f64-4ea7-a7bc-1230a642d574)

`studio_fastpath 1`
![35hp_nahuatl0010](https://github.com/mikkokko/csldr/assets/43149567/818bd98d-b014-472b-b5b8-368b80b7d942)

it's funny that the studiomodel rendering code somehow affects hud rendering
![zr_dust_laskurid0000](https://github.com/mikkokko/csldr/assets/43149567/5cad0736-0750-4984-8ea3-a8c73e68ddbe)

i also had a crash here while playing on a server
![image](https://github.com/mikkokko/csldr/assets/43149567/e95e2498-7bed-42e0-98cc-e81f7b039b63)

**Comment by zengelma** [comment]
my fov changed or smth happened. how can i fix6 help me

**Comment by mikkokko** [comment]
Latest release can render low poly models with the engine's fixed pipeline renderer which should help a bit with this. Can't do much else about this without rewriting all of the entity rendering code.
