### ISSUE TITLE
Crash with `glGetString` after system migrating

### ISSUE THREAD

**Issue by Xelson** [mikkokko/csldr#36]
I recently moved my system to a new ssd and I started getting different errors in the work of different software, amd the same happened with csldr unfortunately 
![image](https://github.com/mikkokko/csldr/assets/43149567/6da4c495-c7d4-4ef4-9df8-e03a2c306372)
it's happening all the time i starting the game on caecabf (1.96) and later

and i don't know why but i tried to run an early version of csldr 4795e89 (1.93) for test and got almost the same error but looks like the code with `glGetString` was executed properly, but dropped a system error. The same error happens also on 4a53ea9 (1.94) and  4a53ea9 (1.95)
![image](https://github.com/mikkokko/csldr/assets/43149567/da194873-191f-477b-a997-294d9462510e)

**Comment by mikkokko** [comment]
The game is running in software mode, try launching it with -gl

**Comment by Xelson** [comment]
I didn't notice it, now everything works, thanks!
