### ISSUE TITLE
Half Life 25th anniversary update broke csldr

### ISSUE THREAD

**Issue by DarkReaper231** [mikkokko/csldr#37]
When you try to run the game it says: "Could not load client_orig.so". There seems to be some tiny difference between pre-anniversary client and post-anniversary client. I can confirm this because when you install counter strike 1.6, Half Life automatically reverts to the new update even tho I have picked the pre-anniversary branch.

**Comment by DarkReaper231** [comment]
Actually the anniversary broke Counter Strike 1.6 in general. When running clean version, it says it can't load client.so. This is problem on Vlave's side. Anyway switching Half-Life back to pre-anniversary fixes everything.

**Comment by SamuelGogarty** [comment]
> Actually the anniversary broke Counter Strike 1.6 in general. When running clean version, it says it can't load client.so. This is problem on Vlave's side. Anyway switching Half-Life back to pre-anniversary fixes everything.

how exactly did you restore the game pre-anniversary?

**Comment by mikkokko** [comment]
they've fixed it
