### ISSUE TITLE
Can optimize the model which have large amount of faces or vertexes?

### ISSUE THREAD

**Issue by WhiteGiveManTao** [mikkokko/csldr#39]
When I use high-poly(about 20k) models(weapons,players etc) to play CS,It will lose many FPS(Even 30FPS) when I add 29 bots(any addons like SyPB,YaPB,Ebot or ZBOT(Official Bots))

**Comment by WhiteGiveManTao** [comment]
I Suggest that Update the Renderer about OpenGL,few of players use Software renderer

**Comment by mikkokko** [comment]
If studio_fastpath doesn't improve performance with high poly models, there's nothing else I can do.
