### ISSUE TITLE
Players receive "Reliable channel overflowed" when hosting server

### ISSUE THREAD

**Issue by unattendedplayer** [mikkokko/csldr#40]
If player hosts a listenserver with csldr installed, anybody who tries to connect to his server will receive "Reliable channel overflowed" message and fail to join.
Steps to reproduce:
Install csldr on Counter-Strike. Create a server using "New Game". Connect to the created server from another machine.
It's important to fix it as people don't like to use HLDS to create a server for casual game.
Tested builds: 4554 & 8684

**Comment by Polarhigh** [comment]
It's caused by these lines: https://github.com/mikkokko/csldr/blob/main/csldr/view.c#L350-L351
I haven't dived into this issue much, but it causes the host to spam SVC_NEWMOVEVARS to all clients.

**Comment by mikkokko** [comment]
Thanks for looking into this @Polarhigh, should be fixed in 6f82e350ef028437b222a529b9175a5fc0c6af39. I'll make a new release when I get home next weekend.
