### ISSUE TITLE
cs not being able to load clientorig.dll (?)

### ISSUE THREAD

**Issue by Antigen5** [mikkokko/csldr#45]
so, i got a new computer and decided to install this mod again since it makes cs way better for me, i rename the original dll file in cl_dlls to clientorig,dllbak and i move the csldr dll from my downloads folder to the cl_dlls folder, once i do that, cs decides to spit out the error that **it cannot load clientorig.dll**.
after that, you can press ok on the error and the game just closes itself, i've tried on the beta version, the steam_legacy version, and the newest anniversary update, but still to no avail, i've tried everything, i do not know what is causing this issue.
![image_2024-03-31_193047222](https://github.com/mikkokko/csldr/assets/68779578/c6fea092-b727-42cd-b9b0-75be6c9286fd)

**Comment by mikkokko** [comment]
Can you send a screenshot of your cl_dlls folder?

**Comment by Antigen5** [comment]
> Can you send a screenshot of your cl_dlls folder?

![image](https://github.com/mikkokko/csldr/assets/68779578/33c59aca-9f73-4065-b828-572077c69406)
here it is, i'm using the steam_legacy version of cs 1.6

**Comment by mikkokko** [comment]
You need to name it to client_orig.dll like the instructions and the error dialog say, not clientorig.dllbak

**Comment by Antigen5** [comment]
> You need to name it to client_orig.dll like the instructions and the error dialog say, not clientorig.dllbak

i renamed it and now it works perfectly, i didn't read the instructions well, thank you either way
