### ISSUE TITLE
game crash after launch 

### ISSUE THREAD

**Issue by FRAJOoOSK** [mikkokko/csldr#46]
game crash after launch .

**Comment by mikkokko** [comment]
What version of the game do you have? Do you have any other client side mods like metahook installed?

**Comment by FRAJOoOSK** [comment]
Original clear installation from Steam.
And I don't have any client-side mods.
I was using it normally until like 2 days ago it just stopped working. I tried reinstalling CS but it doesn't work.

**Comment by mikkokko** [comment]
Do older versions of csldr work? I'd suggest trying v1.96 and/or v1.92.
