### ISSUE TITLE
Add ev_hldm.cpp and hl_events.cpp and configure it to support CS/CZ

### ISSUE THREAD

**Issue by deathreaperz** [mikkokko/csldr#47]
I was trying to make a new weapon with ReGameDLL with this tutorial https://youtu.be/KpMGWy9JjFQ?si=t9y4yKemdCzKm85a . Turned out I'm missing a core stuff which is event fire, made the weapon shot invisible like in the video minute 10.14 . Can you please add ev_hldm.cpp and hl_event.cpp to support CSCZ?

**Comment by mikkokko** [comment]
Out of scope for this project. cs16-client should have what you need.
