### ISSUE TITLE
Maybe I'm Stupid (OK I know I am)

### ISSUE THREAD

**Issue by WhenPlanesFly** [mikkokko/csldr#48]
Hey,  as the title says, I am stupid :)
The problem I'm having is whenever I replace client.dll with csldr's client.dll (and, following the directions, renaming the original client.dll client_orig.dll) the updater will detect the changes and 'update' the client.dll.  I've tried renaming the installer, removing it, and loads of Googling.  I'm running CS 1.6 via Lutris on Arch Linux (not ideal, but whatever.) Any help will be appreciated.  Thanks!

**Comment by mikkokko** [comment]
What updater are you referring to?

**Comment by WhenPlanesFly** [comment]
Updater.exe, the CS 1.6 updater.  Sorry, i'm in a strange situation.  My main PC's motherboard got fried and this PC can't handle CSGO/CS2, so i decided to try CS 1.6.  This is a cracked version, so maybe Updater.exe isn't actually meant to be a part of it?  I think it is though because it looks like the in-game menu when it pops up a window saying it's replacing client.dll

**Comment by xplshn** [comment]
You downloaded an unofficial client, probably GSclient, please try with a "clean" version. This one's good: `https://loadcs.com/download/editions/1/direct`, there are also other editions in the site, ones with "better" graphics, etc.
