### ISSUE TITLE
Old legacy model camera bob (up/down)

### ISSUE THREAD

**Issue by SkyLLerGithub** [mikkokko/csldr#49]
_This really isn't an issue and I do deeply apologize, however this might be the only way I can reach out to you_

Is there a way I can revert the viewmodel bob to sync with the camera so the camera bobs up and down together with the view model like vanilla CS? Instead of the camera being static. (Without reverting the enhancement of course)

_I truly apologize for this as I know this is inappropriate._

**Comment by mikkokko** [comment]
huh i thought i pushed the cvar to toggle it but i didn't, fixed in 5b92e4d51d0b01e0ac2e8d0ef24ed72d2f46caf7.
