### ISSUE TITLE
View model is displayed inverted when the shield is used and new render enabled

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#50]
### Steps to Reproduce
1. Enable `studio_fastpath 1`.
2. Enter the game and buy shield.

### Expected Result
Normal view model display.

### Actual Result
The model looks “turned inside out.”

### Environment
OS: Linux
CS: Steam CS, build 9911
csldr: v1.99

### Additional Materials
- The knife model is displayed normally.
- Bug does not appear with `cl_rigthhand 0`, but then the knife model is not displayed correctly.

`studio_fastpath 1`:

![20240505113221_1](https://github.com/mikkokko/csldr/assets/47604048/f51fe1ed-ea7b-4ac7-b000-23c5b15546da)
![20240505113152_1](https://github.com/mikkokko/csldr/assets/47604048/35235022-d201-470f-9c9e-99dbca92ab37)

`studio_fastpath 0`:

![20240505113218_1](https://github.com/mikkokko/csldr/assets/47604048/30a5c84e-799a-4a34-9331-545009d3ee76)

**Comment by SkyLLerGithub** [comment]
![image](https://github.com/mikkokko/csldr/assets/161835713/bad56c6f-16bf-4373-8efa-c0cf6fa2b3f9)
same here, can confirm

**Comment by mikkokko** [comment]
fixed in 9d430cd6b8288c91d736cd9e57960dba318ad35f
