### ISSUE TITLE
bobbing animations are ridiculously high while spectating & cl_camera_bob in spectating mode

### ISSUE THREAD

**Issue by SkyLLerGithub** [mikkokko/csldr#52]
Hello!
I apologize for this as in my previous issue I forgot clarify the previous issue with camera bobbing while spectating.
The camera is supposed bob up and down while spectating, but my previous issue was that in free look mode it would bob up and down. It seems that you have completely removed the camera bobbing with spectating mode.
(In vanilla game the camera do bob up and down in first person mode while spectating, but not in free look mode)

Also now the animations would bob up and down ridiculously high, like the video shown below.

https://github.com/mikkokko/csldr/assets/161835713/e10dc1b0-8b80-45ec-99fe-8ce510576cec

To my testing with cl_bobstyle 2 this doesn't happen, but even with cl_bobstyle 1 it will still use the games default bobbing style for spectating mode in first person (in my case cl_bobstyle 0), and the problem will still occur. However, with cl_bobstyle 2 it uses the csgo bobbing animations instead, which does not have this issue.

OS: Linux
Client: Steam CS Pre 25th Build 8684

I would again like to deeply apologize, as I have forgotten to include it in my previous issue. 😅

**Comment by mikkokko** [comment]
should be fixed in 032de6ffb9d1e8a016ed5107b33d3d7af45001c7, can't test it myself right now

**Comment by SkyLLerGithub** [comment]
> should be fixed in [032de6f](https://github.com/mikkokko/csldr/commit/032de6ffb9d1e8a016ed5107b33d3d7af45001c7), can't test it myself right now

I will mark this as closed since I've tested it myself and all the issue above has been fixed, thank you.
