### ISSUE TITLE
fov_horplus no longer an option in 25th anniversary build

### ISSUE THREAD

**Issue by SkyLLerGithub** [mikkokko/csldr#53]
I'm not sure if this is intentional but the fov_horplus option no longer exists in 25th anniversary build
![image](https://github.com/mikkokko/csldr/assets/161835713/ee91008a-0b57-44fe-8054-ab65da61365b)
OS: Linux
Client: Steam 25th Anniversary Build 9911
I personally like Hor+ fov mod better as it fixes a lot of the fov issues on odd resolutions and the regular widescreen fix doesnt do this. But do let me know if it was intentionally removed

**Comment by mikkokko** [comment]
it's intentional
