### ISSUE TITLE
Separate shooting anim with dynamic crosshair work

### ISSUE THREAD

**Issue by SkyLLerGithub** [mikkokko/csldr#54]
In the original game if you disabled cl_dynamiccrosshair u would get a static crosshair but with the shooting animations still expanding the crosshair. This was completely gone in the xhair modifications. (xhair_dynamic_crosshair completely removes any kind of animations including shooting)
It would be ideal to add a cvar toggle for shooting crosshair animations that works with xhair_dynamic_crosshair with its scaling as well.
LMK if it's possible, thanks.

**Comment by mikkokko** [comment]
Added xhair_dynamic_move in db6308d67b573517f1261b3f5375ded1be80a7c5 which works like cl_dynamiccrosshair.
