### ISSUE TITLE
dynamic crosshair only while jump/duck

### ISSUE THREAD

**Issue by FRAJOoOSK** [mikkokko/csldr#55]
HI, 
Please add dynamic crosshair only expend while ducking/jumping.

THX.

**Comment by SkyLLerGithub** [comment]
> also dynamic crosshair is not reacting on knife/grenades at all idk why whould be on all weapons

even in vanilla game the crosshair shouldnt react to knifes and grenades, no?

Also please check https://github.com/mikkokko/csldr/issues/54
