### ISSUE TITLE
cl_bob for counter strike source?

### ISSUE THREAD

**Issue by bakhaa2** [mikkokko/csldr#56]
Hi Mikkokko, i have a question about the cl_bob from csgo, is it possible that you could make one for Counter Strike Source please, that would be great, i would really appreciate that, and could you try making some mods for cs source like csgo radar or csgo Hud if it’s possible, there is a lot of people still playing cs source rather than cs 1.6, so could you make some mods for cs source please. That would be very very nice👍🏻
This was the way to get in touch with you, i know it’s really tough to make such mod.
You did a really good job with cs 1.6 mod, you are the best💪🏻
Much love Mikkokko🫶🏻

**Comment by mikkokko** [comment]
nope
