### ISSUE TITLE
ReAimDetector disable the crosshair

### ISSUE THREAD

**Issue by kovakovi2000** [mikkokko/csldr#57]
If the server hash ReAimDetector installed and in the .ini file the **SEND_PROTECTION_WEAPON** is equal to 1, then the crosshair just disappear. Changing that value to 0 and then restarting the server solve this issue, but it should work without disabling server-sided cheating prevention solution.

https://youtu.be/2ohcU2APlds

Please consider fixing this issue.

**Comment by mikkokko** [comment]
Let me know if this fixes it: https://github.com/user-attachments/files/16118637/client.zip
