### ISSUE TITLE
Disappearing crosshair on some servers with many GUI elements

### ISSUE THREAD

**Issue by imshvc** [mikkokko/csldr#58]
See attachments.

[console-log.txt](https://github.com/user-attachments/files/15997714/console-log.txt)
https://github.com/mikkokko/csldr/assets/102489121/0c95d4a9-7284-4411-a37e-aa83590ca065

**Comment by mikkokko** [comment]
See if this fixes it: https://github.com/mikkokko/csldr/issues/57#issuecomment-2212378016

**Comment by imshvc** [comment]
> See if this fixes it: [#57 (comment)](https://github.com/mikkokko/csldr/issues/57#issuecomment-2212378016)

This fixes the problem. Thanks :)
