### ISSUE TITLE
forcing 4:3 aspect ratio in 16:9

### ISSUE THREAD

**Issue by ntaditya** [mikkokko/csldr#61]
hi, its not really an issue but just a feature.
i feel like the fov in 1920x1080 is way too much i want it to be like 1024x768 stretched styled
there is a video demonstrating this https://www.youtube.com/watch?v=DSjYxBc2Xv0
it would be good if you added a feature like this

**Comment by mikkokko** [comment]
would require changing the vertical fov which is not possible without engine hooks
