### ISSUE TITLE
Invisible Models again on latest release using studio_fastpath 1

### ISSUE THREAD

**Issue by ChaoticKamikaze** [mikkokko/csldr#64]
![20241113183602_1](https://github.com/user-attachments/assets/8f3ebc2d-4fdd-4f49-a6d0-1cb78a60c550)
![20241113183552_1](https://github.com/user-attachments/assets/437eeda5-76e6-4334-bc0f-c441eef9bc88)

Does not happen on v1.993.
I thought it was ReHLDS, ReGame, Reapi or an amxx plugin so I tried a fresh install of CS (on steam) and it still happened.

PC Info
GPU: RTX 3060
CPU: AMD Ryzen 7 5800H

**Comment by mikkokko** [comment]
What map is this? Couldn't replicate it with my tests. While studio_fastpath is 1, try changing studio_fastpath_min_polys to 0 and then to some high value like 999999 to see if it changes anything.

**Comment by mikkokko** [comment]
Should be fixed in the latest release.

**Comment by ChaoticKamikaze** [comment]
![20241114160040_1](https://github.com/user-attachments/assets/5e92450e-97b7-4d12-a7f9-51505a2b246c)
