### ISSUE TITLE
Linux client doesn't start

### ISSUE THREAD

**Issue by Nord1cWarr1or** [mikkokko/csldr#9]
The Linux client does not start with this library. It just opens a black window and instantly closes.
The compilation completed without any errors.

**Comment by mikkokko** [comment]
Works fine for me. See if the game prints anything before shutting down/crashing (can do this by running Steam from the command line). If it crashes, run the game with gdb and see where it happens.

**Comment by Nord1cWarr1or** [comment]
@mikkokko here is all info that printed in console: https://bin.garudalinux.org/?ca0533c7d311cb5e#5N4SjUKGC6r1hrj4CaaRxQaB1TAYsd7aLefwEcAVgixA

> run the game with a debugger and see where it happens.

How can I do it?

**Comment by mikkokko** [comment]
I see from the output that it fails to load client_orig.so before shutting down. Make sure that client_orig.so in the same directory where client.so is. If it's in the correct place, see why it fails to load with dlerror(). You can put something like this to Plat_Dlopen in platform_linux.c:
```c
void *Plat_Dlopen(const char *filename)
{
	void *handle = dlopen(filename, RTLD_NOW);	
	if (!handle)
		printf("dlopen(%s) failed: %s\n", filename, dlerror());
	
	return handle;
}
```

**Comment by Nord1cWarr1or** [comment]
> I see from the output that it fails to load client_orig.so before shutting down. Make sure that client_orig.so in the same directory where client.so is.

Yep, I forgot about that. Sorry for taking your time.
